### ISSUE TITLE
Release on Pypi?

### ISSUE THREAD

**Issue by pombredanne** [hughsie/python-cabarchive#2]
Thanks++ for this that I want to include in https://github.com/nexB/scancode-toolkit/tree/develop/src/extractcode together with my Python bindings for libarchive and 7zip...
Could you consider releasing this on Pypi for convenience?

**Comment by hughsie** [comment]
I'm not really a python developer; python-appstream was only developed until I could use GObjectIntrospection bindings of GCab. I don't really plan on "maintaining" it. Sorry.

**Comment by pombredanne** [comment]
Fair enough! You are likely underestimating yourself but this is good to know if I am taking up to actually include this!

**Comment by pombredanne** [comment]
Do you mind if I release it on Pypi? I would need at least to be able to tag it properly and the setup.py needs a tiny bit of love for proper crediting and doc

**Comment by pombredanne** [comment]
I can do this in a fork or here at your convenience, but I'd like to be sure that you have no objection first

**Comment by hughsie** [comment]
I'm happy to make you a contributor on the original repo if that's easier. It sounds like you know what you're doing more than me.

**Comment by pombredanne** [comment]
Go for it! and thank you

**Comment by pombredanne** [comment]
based on the merge of #3 I can now push on Pypi. I did . I tagged master then `python setup.py bdist_wheel sdist` then `twine upload dist/*` 
This is live at https://pypi.python.org/pypi/cabarchive !
If you can create a user on Pypi and tell me, I will make your the owner of the package there

**Comment by hughsie** [comment]
I'm happy for you to "own" the pypi bit. Thanks for all the patches!

**Comment by hughsie** [comment]
>  If you can create a user on Pypi and tell me, I will make you the owner of the package there

@pombredanne I'm now in a position to actually maintain python-cabarchive; I'm planning to use it for the LVFS so if you could make me a maintainer on PyPi I'll upload a v 0.2.0 which properly supports Python 3. Thanks!

**Comment by pombredanne** [comment]
@hughsie sure thing! what's your PyPI userid?

**Comment by hughsie** [comment]
@pombredanne -- it's `hughsient` -- thanks!

**Comment by pombredanne** [comment]
done!

**Comment by hughsie** [comment]
Many thanks dude, much appreciated.

**Comment by pombredanne** [comment]
@hughsie that's the other way around! I have just been holding the keys for a short period! ;)
