### ISSUE TITLE
Adding documentation

### ISSUE THREAD

**Issue by TristanMisja** [hughsie/python-cabarchive#5]
I recommend that you add documentation for this library. 
It's a bit hard to do things with it without docs.

**Comment by hughsie** [comment]
> I recommend that you add documentation for this library.

It was really designed for old versions of OpenShift, I don't even think I'm using it any more. It was also written well before I knew how to write python properly :/

If you want to depend on it, I think adding some docs, reviewing the API and publishing to pypi is the very least we should do.

**Comment by hughsie** [comment]
@TristanMisja so there might be a big user of this API soon; I've polished it up for Python 3 and added things like type annotations. Would you be able to review some of this and help me add some docs?

**Comment by CyberSecDef** [comment]
Any updates on this?  Sometime as simple as:

Here is how you open a cab

cab = cabarchive.whatever('path to cab file')

or something would be nice

**Comment by hughsie** [comment]
There's https://github.com/hughsie/python-cabarchive/blob/master/cabarchive/test_misc.py which is pretty self explanatory, but I do need to set up sphinx, then read-the-docs and then write a lot of comments. If anyone wants to help i would be very happy.

**Comment by hughsie** [comment]
Available here: https://python-cabarchive.readthedocs.io/en/latest/ -- I told you it was easy :)
